### ISSUE TITLE
Compile error about Particles.cu file

### ISSUE THREAD

**Issue by FantasyVR** [TroyZhai/CPP-Fluid-Particles#1]
`Particles.cu:35`  failed to compile on my PC，Windows10, VS 2017, CUDA 10.0。
```C++
Severity	Code	Description	Project	File	Line	Suppression State
Error		The closure type for a lambda ("lambda [](const float3 &, const float3 &)->float3", defined at F:/OpenSource/CPP-Fluid-Particles/src/Particles.cu:35) cannot be used in the template argument type of a __global__ function template instantiation, unless the lambda is defined within a __device__ or __global__ function, or the lambda is an 'extended lambda' and the flag --expt-extended-lambda is specified	fluidParticle	F:\Programs\NVIDIA\CUDA\v10.1\include\thrust\system\cuda\detail\core\agent_launcher.h	926	
```

**Comment by TroyZhai** [comment]
Hello Rain, thanks for reporting the issue.

As I said in the Readme, due to the fact that some experimental feature is used in the code, please add '--expt-extended-lambda' in the nvcc command line.

**Comment by zhai-xiao** [comment]
Hello Rain, thanks for reporting the issue.

As I said in the Readme, due to the fact that an experimental feature is used in the code, please add '--expt-extended-lambda' in the nvcc command line.
