### ISSUE TITLE
关于边界条件的写法

### ISSUE THREAD

**Issue by houkensjtu** [TroyZhai/CPP-Fluid-Particles#5]
您好！我也是一名从事流体模拟的工作者，在编写代码中，边界条件的设置往往需要和内部场不同的计算式，且各种边界条件的给法也不一样，导致代码非常繁复。甚至往往需要写hard code，只能适应一种网格形状的硬代码，使得代码可重用性很差。
关于这样的问题，请问您有什么好的建议，或者推荐看的代码实例，教材，论文吗？
非常感谢！

**Comment by zhai-xiao** [comment]
抱歉很久没有登录账号，到目前才看到问题。我不太清楚您的具体领域，我所关注的领域仅限于图形学中，对于工程应用理解甚少。目前比较流行的简单流体边界主要是对于压强和速度两个量进行设置的，或者也可以抽象为是对于标量和矢量两种类型的属性进行设置。一个比较简单且有效的例子可以参考2005年的SIGGRAPH论文Discontinuous Fluids

**Comment by houkensjtu** [comment]
你好！我所说的就是针对简单的压强和速度的边界，不是说数学上我不知道形式如何构成，而是在实际计算代码上，如何建立合理的抽象，减少一些比如（if i==0,j==0:...; else if i==0, j==n: ...)这样多重条件的硬代码。

**Comment by zhai-xiao** [comment]
如果是这样的话，可以把边界分为静态和动态两种，分别用两个list存下来每个需要处理的点的位置、法向、数据类型等等信息。静态边界在仿真初始化的时候处理好，动态边界在仿真运行时rasterize。两个list就可以用for_each的方式直接处理，也可以加入并行（但要考虑有些地方需要原子操作）。这样就可以避免过多的if...else...，无论是对于运行速度还是代码的简洁程度都有益 :)

**Comment by houkensjtu** [comment]
谢谢你的建议！这好像的确是一个方法，我准备自己实践试试看。不过根据我简单阅读你的代码，好像在main.cpp里采用的还是手动的指定i,j来施加边界条件的方法，你所说的这个用list存储的方法有什么可以参考的开源代码的例子吗？

**Comment by zhai-xiao** [comment]
main.cpp里是初始化，并不会拖慢运行时的速度，所以没必要先存储再处理。重要的是运行时减少if分支。例子暂时我手头没有哈，不过应该很简单的，建个struct存所有需要的信息，然后用个vector之类的结构就可以了
