### ISSUE TITLE
Compile Fail

### ISSUE THREAD

**Issue by Aiden-Potter** [TroyZhai/CPP-Fluid-Particles#6]
I am not so familiar with CUDA. I have tried to all the requirements you list，But there still a complie bug.
This is bug report:
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified.

Thank you for attension.

**Comment by zhai-xiao** [comment]
Hi @Aiden-Potter, I would suggest checking if there are any spaces in your path. It seems that nvcc thought you provided multiple files but it could be the space in the path. Cheers :)

**Comment by Aiden-Potter** [comment]
Thank you for your help.I have run the demo successfully!   Orz
